name: 'Lint to the Future Dashboard'
description: 'Sets up your lint-to-the-future Dashboard for you'
branding:
  icon: 'award'
  color: 'orange'
inputs:
  folder:
    description: 'The folder to deploy the Lint to the Future dashboard to'
    default: ''
    required: false
  token:
    description: 'Token used to deploy to gh-pages. Should be set to secrets.GITHUB_TOKEN by default'
    required: true
  node-version:
    description: 'The Node.js version to use, passed directly to actions/setup-node node-version field'
    default: '18'
    required: false
  cache:
    description: 'This is passed directly to the actions/setup-node cache field. Refer to their readme for valid values'
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{inputs.node-version}}
        cache: ${{inputs.cache}}
    - run: |
          if [ -f ./pnpm-lock.yaml ]; then
            pnpm i
          elif [ -f ./yarn.lock ]; then
            yarn 
          else
            npm i 
          fi
      shell: bash
    - run: npx lint-to-the-future output -o lttfOutput --rootUrl `cut -d'/' -f2 <<< ${{ github.repository }}`${{ inputs.folder }} --previous-results https://${{ github.repository_owner }}.github.io/`cut -d'/' -f2 <<< ${{ github.repository }}`${{inputs.folder}}/data.json
      shell: bash
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.token }}
        publish_dir: ./lttfOutput
        destination_dir: ./${{ inputs.folder }}